services:
  - type: web
    name: python-test-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
